config/routes.rb
Rails.application.routes.draw do
  resources :sheets
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'sheets#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end


end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  # GET /sheets
  # GET /sheets.json
  def index
    @sheets = Sheet.all
  end

  # GET /sheets/1
  # GET /sheets/1.json
  def show
  end

  # GET /sheets/new
  def new
    @sheet = Sheet.new
  end

  # GET /sheets/1/edit
  def edit
  end

  # POST /sheets
  # POST /sheets.json
  def create
    @sheet = Sheet.new(sheet_params)

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to @sheet, notice: 'Sheet was successfully created.' }
        format.json { render :show, status: :created, location: @sheet }
      else
        format.html { render :new }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sheets/1
  # PATCH/PUT /sheets/1.json
  def update
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @sheet }
      else
        format.html { render :edit }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1
  # DELETE /sheets/1.json
  def destroy
    @sheet.destroy
    respond_to do |format|
      format.html { redirect_to sheets_url, notice: 'Sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sheet_params
      params.fetch(:sheet, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Time Logger" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="top-bar">
    <div class="top-bar-title">
    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
      <button class="menu-icon dark" type="button" data-toggle></button>
    </span>
      <strong>Time Logger</strong>
    </div>
    <div id="responsive-menu">
      <div class="top-bar-right">
        <ul class="menu">
          <% if user_signed_in? %>
              <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>

  <%= display_flash_messages %>
    <%= yield %>

  </body>
</html>

app/views/sheets/_form.html.erb
<%= form_for(@sheet) do |f| %>
  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
      <% @sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/edit.html.erb
<h1>Editing Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<h1>Listing Sheets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= link_to 'Show', sheet %></td>
        <td><%= link_to 'Edit', edit_sheet_path(sheet) %></td>
        <td><%= link_to 'Destroy', sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sheet', new_sheet_path %>

app/views/sheets/new.html.erb
<h1>New Sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', sheets_path %>

app/views/sheets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sheet_path(@sheet) %> |
<%= link_to 'Back', sheets_path %>